# ToDo: automate for file changes
variables:
  QA_IMAGE_VERSION: 1

# To use Docker to build Docker images
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info

stages:
  - qa_prerequisite
  - lint

build-qa-image:
  stage: qa_prerequisite
  image: docker:24.0.5-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f Dockerfile.qa -t ${CI_REGISTRY_IMAGE}:${QA_IMAGE_VERSION} .
    - docker push ${CI_REGISTRY_IMAGE}:${QA_IMAGE_VERSION}
  rules:
    - changes:
      - requirements_qa.txt
      - Dockerfile.qa
      when: always
    - when: never

.lint:
  stage: lint
  image: $CI_REGISTRY_IMAGE:$QA_IMAGE_VERSION
  before_script:
    - cat pyproject.toml

lint:flake8:
  extends: .lint
  script:
    - flake8 -v --config=pyproject.toml src/ test/

lint:black:
  extends: .lint
  script:
    - black -v --config pyproject.toml --check src/ test/

lint:mypy:
  extends: .lint
  script:
    - mypy --verbose --config-file pyproject.toml src/
