variables:
  QA_IMAGE_VERSION: 1  # ToDo: automate for file changes

stages:
  - qa_prerequisite
  - lint

build-qa-image:
  stage: qa_prerequisite
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f Dockerfile.qa -t ${CI_REGISTRY_IMAGE}:{QA_IMAGE_VERSION} .
    - docker push ${CI_REGISTRY_IMAGE}
  only:
    changes:
      - requirements_qa.txt
      - Dockerfile.qa

.lint:
  stage: lint
  image: $CI_REGISTRY_IMAGE:$QA_IMAGE_VERSION
  before_script:
    - cat pyproject.toml

lint:flake8:
  extends: .lint
  script:
    - flake8

lint:black:
  extends: .lint
  script:
    - black --check

lint:mypy:
  extends: .lint
  script:
    - mypy .
